name: Build and Push

on: push

permissions:
  contents: read

env:
  IMAGE_NAME: appwrite/base
  REGISTRY: docker.io
  TAG: ${{ github.event.release.tag_name }}

# https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
# https://learn.arm.com/learning-paths/cross-platform/github-arm-runners/actions/
jobs:
  container_build_and_push:
    if: github.ref != 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image from Dockerfile
        run: |
          docker image build --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{matrix.arch}} .

      - name: Push an image
        run: |
          docker image push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{matrix.arch}}

  manifest_build_and_push:
    if: github.ref != 'refs/heads/main'
    needs: container_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest
        run: |
            docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64

      - name: Push manifest
        run: |
            docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.SHA }}
