name: Verify Automation

on: push

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate Composer configuration
        run: composer validate --strict

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Check Composer platform requirements
        run: composer check-platform-reqs

      - name: Verify PHP automation
        run: composer verify
